Remove conflicting import
Tests were failing due to error[E0659]: `panic` is ambiguous.

Co-Authored-By: Korinna Pinakoulakis <7438240+kpinakula@users.noreply.github.com>